### ISSUE TITLE
Community To-Do list

### ISSUE THREAD

**Issue by jordanbancino** [jordanbancino/JavaEssentials#27]
# Description
Here’s what the Reddit community over at [/r/java](https://reddit.com/r/java) suggested for this library:

- [ ] Rename JavaEssentials to remove the word “Java” from the name
    - [ ] Pick a new name
    - [ ] Redesign logo
    - [ ] Refactor code
    - [ ] Refactor the README document
- [ ] Rename most variables to follow the standard convention for Java
- [ ] Upload builds to Maven Central
- [ ] Convert classes from using static methods to using non-static, instantiatable forms
- [ ] Test code 

# Technical Information
| Information | Value |
|--|--|
| Effected JavaEssentials versions | 3.0+ |
| Java versions | Irrelevant  |

**Comment by jordanbancino** [comment]
Next stop: [/r/javahelp](https://reddit.com/r/javahelp)

Here what I’ll ask them:

- [ ] How do I test my code effectively?
- [ ] What should I rename this project to?

**Comment by jordanbancino** [comment]
See additional comments and to-do items here: https://www.reddit.com/r/java/comments/86pxo3/new_java_library/
